### ISSUE TITLE
I found a problem when I ran custom-elements

### ISSUE THREAD

**Issue by lhzxxy** [bpmn-io/bpmn-js-examples#78] opened 2018-12-21 03:09 UTC
I drew firstly a BPMN diagram like this:
![image](https://user-images.githubusercontent.com/39483165/50321972-3649d480-050e-11e9-9bb4-6730e9af9532.png)
Then I wanted to create a pool, but I found that:
![image](https://user-images.githubusercontent.com/39483165/50322257-49a96f80-050f-11e9-85e9-e809c73c60f4.png)
and could not  modify this diagram any more.
![image](https://user-images.githubusercontent.com/39483165/50322583-99d50180-0510-11e9-8c38-4f7834190af4.png)

**Comment by pinussilvestrus** [comment] 2019-01-02 07:53
Please try to first open a thread in our [forum](https://forum.bpmn.io/) before opening a Github issue. In the forum try to give us more information, e.g. with example code or a test case so we can help you in detail.

**Comment by lhzxxy** [comment] 2019-01-02 18:16
> Should be possible to reproduce, given the steps provided or am I wrong?
> 
> * Open Example
> * Create shown diagram
> * Wrap diagram in participant
> * See that diagram cannot be interacted with anymore

Thank you, I have open a [thread](https://forum.bpmn.io/t/an-exception-occurs-when-a-pool-is-placed-on-a-custom-element/2982/3) in the forum, and the steps are shown in the gif.

**Comment by pinussilvestrus** [comment] 2021-01-20 08:20
I am not able to reproduce this anymore with the current [custom elements example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/custom-elements). I'm closing the issue though, feel free to re-open once things changed.

**Closed by pinussilvestrus** 2021-01-20 08:20 UTC
Labels: backlog, bug, spring cleaning
