### ISSUE TITLE
properties-panel (V3.4): bo.get is not a function

### ISSUE THREAD

**Issue by MicroLord** [bpmn-io/bpmn-js-examples#92] opened 2019-04-29 03:37 UTC
for bpmn-js-examples :
create diagram bug : bo.get is not a function

![image](https://user-images.githubusercontent.com/10664096/56875348-e73f1d80-6a72-11e9-8f4a-71e9370b06a3.png)

**Comment by nikku** [comment] 2019-04-29 06:22
Could you provide some more context? Which example did you try out? How did you trigger the error?

**Comment by MicroLord** [comment] 2019-04-29 07:36
> Could you provide some more context? Which example did you try out? How did you trigger the error?

properties-panel module 
change version to 3.3.1 , worked 
you should test

**Comment by zenithpolar** [comment] 2019-04-30 17:09
I got the same error trying to open or create a new diagram in the **properties-panel** example . As @MicroLord said, changing the bpmn-js dependency from 3.4.1 to 3.3.x make it works for some reason. As far as I tested it, it works normally this way, thanks for the sugestion.

**Comment by nikku** [comment] 2019-04-30 17:57
This is an actual bug with our latest `bpmn-js` release. Now we do clear the diagram in cases where we previously did not ([relevant diff](https://github.com/bpmn-io/bpmn-js/compare/v3.3.1...master#diff-403c08b3642c7a9f03c30aae67d46a9aL361)). 

@barmac Could you have a look what is going on here?

**Comment by barmac** [comment] 2019-05-02 08:17
Actually, this is caused by a bug within `bpmn-js-properties-panel` module which has been already fixed in `0.24.2`. Fix is applied [here](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/198a48d41f9343929ec041f26930d0a421eff11a/lib/PropertiesPanel.js#L258).

I will update the dependency and it's going to work fine.

**Comment by barmac** [comment] 2019-05-02 09:55
Closed via https://github.com/bpmn-io/bpmn-js-examples/pull/93

**Closed by barmac** 2019-05-02 09:55 UTC
Labels: bug, needs review
