### ISSUE TITLE
bpmn-properties example appears to be missing

### ISSUE THREAD

**Issue by kirstenhh** [bpmn-io/bpmn-js-examples#181] opened 2022-08-22 12:56 UTC
__Describe the Bug__

The src folder appears to be missing from the bpmn-properties example 

__Steps to Reproduce__

Visit [the bpmn-properties folder](https://github.com/bpmn-io/bpmn-js-examples/tree/master/bpmn-properties)
This does not appear to be a complete Node.js project

**Comment by pinussilvestrus** [comment] 2022-08-25 10:05
I think the example is more about `docs` and some test cases to illustrate. There are no dedicated `src` files, it's still a valid Node.js project though.

I'm closing this one as it is as intended. Feel free to re-open in case you disagree 👍

**Closed by pinussilvestrus** 2022-08-25 10:05 UTC
Labels: bug
