### ISSUE TITLE
Minimap Error

### ISSUE THREAD

**Issue by mrkekko92** [bpmn-io/bpmn-js-examples#99] opened 2019-07-26 12:52 UTC
Hi, when I try to add the minimap to the modeler I get this error, can anyone help me?

![minimapError](https://user-images.githubusercontent.com/52780907/61952757-020f2880-afb5-11e9-9eb2-6b076ab3f5b1.PNG)

**Comment by philippfromme** [comment] 2019-07-29 07:25
Can you see the actual error? What does your setup look like?

**Comment by mrkekko92** [comment] 2019-07-30 07:26
My setup config is:

var bpmnModeler = new CustomModeler({
    container: '#js-canvas',
    propertiesPanel: '#js-properties-panel',
     additionalModules: [
      minimapModule
    ] 
  })

export default {
  __init__: [ 'bpmnRules','paletteProvider', 'contextPadProvider', 'replaceMenuProvider','minimap'],
  bpmnRules: [ 'type', CustomRules ],
  paletteProvider: [ 'type', CustomPaletteProvider ],
  replaceMenuProvider: [ 'type', CustomReplaceMenuProvider ],
  contextPadProvider: [ 'type', CustomContextPadProvider ],
  minimap:['type',Minimap]
}

![error listener](https://user-images.githubusercontent.com/52780907/62109184-0769bd00-b2ac-11e9-8b07-9b3f4ba98c64.PNG)

**Comment by nikku** [comment] 2019-07-30 07:28
Please [format your code snippets](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code).

**Comment by mrkekko92** [comment] 2019-07-30 07:34
![image](https://user-images.githubusercontent.com/52780907/62109676-12711d00-b2ad-11e9-93da-9925846084df.png)

![image](https://user-images.githubusercontent.com/52780907/62109712-2452c000-b2ad-11e9-95ae-5eb82fa055e0.png)

Sorry, with images maybe it's easier to understand.

**Comment by nikku** [comment] 2019-07-30 07:35
Did you checkout the link in my previous comment? I was referring to adding proper formating in your post.

**Comment by philippfromme** [comment] 2019-07-30 07:47
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet 🥂

**Comment by mrkekko92** [comment] 2019-07-30 07:51
Sorry but I'm not very practical, should it be okay?

```
var bpmnModeler = new CustomModeler({
    container: '#js-canvas',
    propertiesPanel: '#js-properties-panel',
     additionalModules: [
      minimapModule
    ] 
  })

export default {
  __init__: [ 'bpmnRules','paletteProvider', 'contextPadProvider', 'replaceMenuProvider','minimap'],
  bpmnRules: [ 'type', CustomRules ],
  paletteProvider: [ 'type', CustomPaletteProvider ],
  replaceMenuProvider: [ 'type', CustomReplaceMenuProvider ],
  contextPadProvider: [ 'type', CustomContextPadProvider ],
  minimap:['type',Minimap]
}
```

**Comment by nikku** [comment] 2019-07-30 07:55
Thanks :heart:

**Comment by nikku** [comment] 2019-07-30 07:57
Is it possible for you to put a minimal working example of what you're doing on GitHub? Not sure what your `export default` module is, not sure why you load the `minimap` twice.

The right instantiation for the properties panel is:

```
new BpmnJS({
  propertiesPanel: {
    parent: '#properties-container'
  }
});
```

**Comment by mrkekko92** [comment] 2019-07-30 08:26
I'll explain, I'm customizing bpmn modeler js for zeebe, now I'll post the configuration of what I'm doing.

# CustomModeler 
```
import Modeler from 'bpmn-js/lib/Modeler';
import propertiesPanelModule from 'bpmn-js-properties-panel';
import propertiesProviderModule from './custom/properties-provider';
import camundaModdleDescriptor from './custom/zeebe-bpmn-moddle/zeebe';
import CustomModule from './custom';
import CustomModelingModule from './custom/modeling';

export default class CustomModeler extends Modeler {

  constructor(options) {

    var modelerOptions = {
      container: options.container,
      keyboard: { bindTo: document },
      propertiesPanel: {
        parent: options.propertiesPanel
      },
      moddleExtensions: {
        camunda: camundaModdleDescriptor
      }
    };
    super(modelerOptions);
  }

  resetZoom(callback) {
    var self = this;
    self.get('zoomScroll').reset();
  }
}

CustomModeler.prototype._modules = [
  ...CustomModeler.prototype._modules,
  CustomModule,
  propertiesPanelModule,
  propertiesProviderModule,
  CustomModelingModule
];
```

# Custom Module

```
import CustomPaletteProvider from './CustomPaletteProvider';
import CustomReplaceMenuProvider from './CustomReplaceMenuProvider';
import CustomContextPadProvider from './CustomContextPadProvider';
import CustomRules from './CustomRules';
import Minimap from 'diagram-js-minimap/lib/Minimap'

export default {
  __init__: [ 'bpmnRules','paletteProvider', 'contextPadProvider', 'replaceMenuProvider','minimap'],
  bpmnRules: [ 'type', CustomRules ],
  paletteProvider: [ 'type', CustomPaletteProvider ],
  replaceMenuProvider: [ 'type', CustomReplaceMenuProvider ],
  contextPadProvider: [ 'type', CustomContextPadProvider ],
  minimap:['type',Minimap]
}
```

# Declaration

```
var bpmnModeler = new CustomModeler({
    container: '#js-canvas',
    propertiesPanel: '#js-properties-panel',
     additionalModules: [
      minimapModule
    ] 
  })

```

However, even if I simply try to use the minimap module at the bpmn Viewer without customizations, I always get the error I posted earlier.

**Comment by nikku** [comment] 2019-07-31 08:49
As mentioned, you do not properly configure the properties panel.

The error goes away, once you've removed the minimap from your setup?

**Comment by mrkekko92** [comment] 2019-07-31 08:56
Yes, the error goes away when the minimap is not added.

**Comment by nikku** [comment] 2019-07-31 08:57
Please provide us with a setup that allows us to reproduce your bug (i.e. a project created on GitHub). Otherwise we won't be able to help you.

**Comment by nikku** [comment] 2019-08-05 12:40
Closing this due to missing steps to reproduce.

**Closed by nikku** 2019-08-05 12:40 UTC
Labels: help wanted
